## for now - orange pi is supported.
HARDWARE=orangepi
## Put your hostname here
HOSTNAME=orangebox
## Active user (orangepi default one for orangepi, pi - for raspberry pi)
USER=orangepi
## SSID name
SSID_NAME=orangeBox
## SSID password
SSID_PASSWORD=not4youreyes

## below are settings of WEBUI. Don't change them, until you don't know what are you doing
WEBUI_USER=webui
WEBUI_LOCATION=/opt/webui

## below are settings of i2p. Don't change them, until you don't know, what are you doing
I2P_USER=$USER
I2P_LOCATION=/opt/i2p

