#! /bin/sh
### BEGIN INIT INFO
# Provides:          i2p
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: i2p anonymizing proxy
# Description:       i2p router, java based
### END INIT INFO

# Do NOT "set -e"
# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=/opt/i2p/i2prouter
USER=orangepi
STARTSCRIPT=/usr/local/bin/starti2p.sh
STOPSCRIPT=/usr/local/bin/stopi2p.sh
DESC="i2p"
NAME=i2p
SCRIPTNAME=/etc/init.d/$NAME

test -x $DAEMON || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh
# I like to know what is going on
VERBOSE=yes


. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting i2p proxy" "i2p"
        su -c "$STARTSCRIPT&" $USER 
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping i2p proxy" "i2p"
        su -c "$STOPSCRIPT" $USER
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    $DAEMON status
    ;;
  *)
    echo "Usage: /etc/init.d/$SCRIPTNAME {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
